### ISSUE TITLE
Code availability for data_gatherer

### ISSUE THREAD

**Issue by mangstad** [ABCD-STUDY/abcd-dicom2bids#4]
Is it possible to provide the non-complied code for the data_gatherer function?

Also, any word on whether (or when) the QC info required by this will be available on NDA? Or if it already is, when this will be updated to use those files rather than the proprietary ones?

**Comment by ericearl** [comment]
@mangstad Thanks for the issue! I didn't realize the `data_gatherer.m` code wasn't in this repo.  Sorry, it looks like I have some git history to clean up from here and appropriately release.  I'll close this issue when I resolve that, but here it is for now:

https://github.com/DCAN-Labs/abcd-dicom2bids/blob/Documentation_and_bug_fix/src/data_gatherer.m

As for the official QC info, I haven't heard an update from the DAIC or the NDA for about a month or two.  There's still no timeline since then.  @HaukeBartsch is there anyone there from the DAIC on GitHub I can tag to answer the second part of this issue?

**Comment by ericearl** [comment]
@mangstad The pull request #5 (release v2.0.0) here should take care of this issue.
